from .usuarios import Usuario as UsuarioResource
from .usuarios import Usuarios as UsuariosResource
from .usuariosalumno import UsuarioAlumno as UsuarioAlumnoResource
from .usuariosalumno import UsuariosAlumnos as UsuariosAlumnosResource
from .usuariosalumno import UsuarioProfesor as UsuarioProfesorResource
from .login import Login as LoginResource
from .pago import Pago as PagoResource
from .planificacion import PlanificacionAlumno as PlanificacionAlumnoResource
from .planificacion import PlanificacionProfesor as PlanificacionProfesorResource
from .planificacion import PlanificacionesProfesores as PlanificacionesProfesoresResources
from .profesor import ProfesorClases as ProfesorClasesResource
