from .usuarios import Usuario as UsuarioResource
from .usuarios import Usuarios as UsuariosResource
from .usuariosalumnos import UsuarioAlumno as UsuarioAlumnoResource
from .usuariosalumnos import UsuariosAlumnos as UsuariosAlumnosResource
from .usuarioprofesores import UsuarioProfesor as UsuarioProfesorResource
from .usuarioprofesores import UsuariosModel as UsuarioModelResource
from .login import Login as LoginResource
from .pago import Pago as PagoResource
from .planificacion import PlanificacionAlumno as PlanificacionAlumnoResource
from .planificacion import PlanificacionProfesor as PlanificacionProfesorResource
from .clases import ClasesProfesores as ClasesProfesorResource
from .clases import ClasesAlumnos as ClasesAlumnosResoure
from .clases import Clase as ClaseResource
from .clases import Clases as ClasesResource
