from .usuarios import Usuario as UsuarioResource
from .usuarios import Usuarios as UsuariosResource
from .usuarios import UsuarioAlumno as UsuarioAlumnoResource
from .usuarios import UsuariosAlumnos as UsuariosAlumnosResource
from .usuarios import UsuarioProfesor as UsuarioProfesorResource
from .login import Login as LoginResource
from .pago import Pago as PagoResource
from .planificacion import PlanificacionAlumno as PlanificacionAlumnoResource
from .planificacion import PlanificacionProfesor as PlanificacionProfesorResource
from .profesor import ProfesorClases as ProfesorClasesResource
