"""Add imagen field to Clase model

Revision ID: bd3110e62137
Revises: e1f677e9e57f
Create Date: 2026-03-06 18:12:37.747062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3110e62137'
down_revision = 'e1f677e9e57f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clase', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
