"""add foto descripcion to profesor

Revision ID: ee725e8556b8
Revises: bd3110e62137
Create Date: 2026-03-06 18:58:00.485112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee725e8556b8'
down_revision = 'bd3110e62137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('descripcion', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesor', schema=None) as batch_op:
        batch_op.drop_column('descripcion')
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
